//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.05 at 09:09:22 AM BRT 
//


package eventos.s1210;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Pensao alimentícia
 * 
 * <p>Java class for TPensaoAlim complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TPensaoAlim">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cpfBenef">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="\d{11}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="dtNasctoBenef" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nmBenefic">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="2"/>
 *               &lt;maxLength value="70"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="vlrPensao">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="14"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPensaoAlim", namespace = "http://www.esocial.gov.br/schema/evt/evtPgtos/v02_04_01", propOrder = {
    "cpfBenef",
    "dtNasctoBenef",
    "nmBenefic",
    "vlrPensao"
})
public class TPensaoAlim {

    @XmlElement(required = true)
    protected String cpfBenef;
    protected XMLGregorianCalendar dtNasctoBenef;
    @XmlElement(required = true)
    protected String nmBenefic;
    @XmlElement(required = true)
    protected BigDecimal vlrPensao;

    /**
     * Gets the value of the cpfBenef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpfBenef() {
        return cpfBenef;
    }

    /**
     * Sets the value of the cpfBenef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpfBenef(String value) {
        this.cpfBenef = value;
    }

    /**
     * Gets the value of the dtNasctoBenef property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDtNasctoBenef() {
        return dtNasctoBenef;
    }

    /**
     * Sets the value of the dtNasctoBenef property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDtNasctoBenef(XMLGregorianCalendar value) {
        this.dtNasctoBenef = value;
    }

    /**
     * Gets the value of the nmBenefic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNmBenefic() {
        return nmBenefic;
    }

    /**
     * Sets the value of the nmBenefic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNmBenefic(String value) {
        this.nmBenefic = value;
    }

    /**
     * Gets the value of the vlrPensao property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVlrPensao() {
        return vlrPensao;
    }

    /**
     * Sets the value of the vlrPensao property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVlrPensao(BigDecimal value) {
        this.vlrPensao = value;
    }

}
