//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.09 at 09:40:59 AM BRT 
//


package lote.retornoEnvio;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the lote.retornoEnvio package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: lote.retornoEnvio
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TOcorrencias.Ocorrencia }
     * 
     */
    public TOcorrencias.Ocorrencia createTOcorrenciasOcorrencia() {
        return new TOcorrencias.Ocorrencia();
    }

    /**
     * Create an instance of {@link TIdeEmpregador }
     * 
     */
    public TIdeEmpregador createTIdeEmpregador() {
        return new TIdeEmpregador();
    }

    /**
     * Create an instance of {@link TOcorrencias }
     * 
     */
    public TOcorrencias createTOcorrencias() {
        return new TOcorrencias();
    }

    /**
     * Create an instance of {@link TStatus }
     * 
     */
    public TStatus createTStatus() {
        return new TStatus();
    }

    /**
     * Create an instance of {@link TDadosRecepcao }
     * 
     */
    public TDadosRecepcao createTDadosRecepcao() {
        return new TDadosRecepcao();
    }

    /**
     * Create an instance of {@link ESocial.RetornoEnvioLoteEventos }
     * 
     */
    public ESocial.RetornoEnvioLoteEventos createESocialRetornoEnvioLoteEventos() {
        return new ESocial.RetornoEnvioLoteEventos();
    }

    /**
     * Create an instance of {@link ESocial }
     * 
     */
    public ESocial createESocial() {
        return new ESocial();
    }

    /**
     * Create an instance of {@link TIdeTransmissor }
     * 
     */
    public TIdeTransmissor createTIdeTransmissor() {
        return new TIdeTransmissor();
    }

}
