//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.24 at 11:45:42 PM BRT 
//


package lote.envio;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the lote.envio package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: lote.envio
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TArquivoEsocial }
     * 
     */
    public TArquivoEsocial createTArquivoEsocial() {
        return new TArquivoEsocial();
    }

    /**
     * Create an instance of {@link ESocial }
     * 
     */
    public ESocial createESocial() {
        return new ESocial();
    }

    /**
     * Create an instance of {@link ESocial.EnvioLoteEventos }
     * 
     */
    public ESocial.EnvioLoteEventos createESocialEnvioLoteEventos() {
        return new ESocial.EnvioLoteEventos();
    }

    /**
     * Create an instance of {@link TIdeEmpregador }
     * 
     */
    public TIdeEmpregador createTIdeEmpregador() {
        return new TIdeEmpregador();
    }

    /**
     * Create an instance of {@link ESocial.EnvioLoteEventos.Eventos }
     * 
     */
    public ESocial.EnvioLoteEventos.Eventos createESocialEnvioLoteEventosEventos() {
        return new ESocial.EnvioLoteEventos.Eventos();
    }

    /**
     * Create an instance of {@link TIdeTransmissor }
     * 
     */
    public TIdeTransmissor createTIdeTransmissor() {
        return new TIdeTransmissor();
    }

}
