//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.24 at 11:51:23 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.esocial.gov.br/schema/lote/eventos/envio/retornoProcessamento/v1_3_0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package consulta.retornoProcessamento;
