//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.24 at 06:06:24 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.esocial.gov.br/schema/lote/eventos/envio/consulta/retornoProcessamento/v1_0_0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package consulta.envioConsulta;
