//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.05 at 12:24:36 AM BRT 
//


package eventos.s1040;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Informações da Função
 * 
 * <p>Java class for TDadosFuncao complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TDadosFuncao">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dscFuncao">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codCBO">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="\d{4,6}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TDadosFuncao", namespace = "http://www.esocial.gov.br/schema/evt/evtTabFuncao/v02_04_01", propOrder = {
    "dscFuncao",
    "codCBO"
})
public class TDadosFuncao {

    @XmlElement(required = true)
    protected String dscFuncao;
    @XmlElement(required = true)
    protected String codCBO;

    /**
     * Gets the value of the dscFuncao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDscFuncao() {
        return dscFuncao;
    }

    /**
     * Sets the value of the dscFuncao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDscFuncao(String value) {
        this.dscFuncao = value;
    }

    /**
     * Gets the value of the codCBO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodCBO() {
        return codCBO;
    }

    /**
     * Sets the value of the codCBO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodCBO(String value) {
        this.codCBO = value;
    }

}
